spring:
  datasource:
    url:
      jdbc:mysql://localhost:3306/xxq?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username:
      root
    password:
      wangzibin666
    driver-class-name:
      com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  tomcat:
    max-swallow-size: 100MB
  port: 9099  # 设置 Spring Boot 应用的启动端口为 9099


# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: wzb.springboot.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

